// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4S0Aipcc3eqLjk-5oED1MjKkB872ICnU',
    appId: '1:180692410992:web:93f6f1158d720df2fdcab5',
    messagingSenderId: '180692410992',
    projectId: 'klik-makan',
    authDomain: 'klik-makan.firebaseapp.com',
    storageBucket: 'klik-makan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbDv37Aaj6bDT9pJ9r4RJABbmv3P32gTQ',
    appId: '1:180692410992:android:cb8c339b8efb1e18fdcab5',
    messagingSenderId: '180692410992',
    projectId: 'klik-makan',
    storageBucket: 'klik-makan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqAL3whlWyzZmMcKCL-F0ZiEiWzUdiv1M',
    appId: '1:180692410992:ios:76edf029df6e5221fdcab5',
    messagingSenderId: '180692410992',
    projectId: 'klik-makan',
    storageBucket: 'klik-makan.firebasestorage.app',
    iosBundleId: 'com.example.klikMakan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqAL3whlWyzZmMcKCL-F0ZiEiWzUdiv1M',
    appId: '1:180692410992:ios:76edf029df6e5221fdcab5',
    messagingSenderId: '180692410992',
    projectId: 'klik-makan',
    storageBucket: 'klik-makan.firebasestorage.app',
    iosBundleId: 'com.example.klikMakan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4S0Aipcc3eqLjk-5oED1MjKkB872ICnU',
    appId: '1:180692410992:web:e209075947166220fdcab5',
    messagingSenderId: '180692410992',
    projectId: 'klik-makan',
    authDomain: 'klik-makan.firebaseapp.com',
    storageBucket: 'klik-makan.firebasestorage.app',
  );

}